### ISSUE TITLE
exception viewing boilerplay.2015-07-30.0.log

### ISSUE THREAD

**Issue by intracer** [KyleU/boilerplay#13]
[IllegalStateException: Invalid main line index [11] for line [699]: [Silhouette] Gravatar API returns status code: 404]

boilerplay.2015-07-30.0.log content at line 699

[INFO] 2015-07-30 19:23:48,779 from com.mohiva.play.silhouette.impl.services.GravatarService in boilerplay-akka.actor.default-dispatcher-5 
[Silhouette] Gravatar API returns status code: 404

**Comment by kyleu** [comment]
Fixed.
