### ISSUE TITLE
Module "es6-promise" not found

### ISSUE THREAD

**Issue by ppet** [KyleU/boilerplay#16]
Hi,

After unzipping the archive, I just run sbt, then sbt run against a very fresh boilerplay-master install.
Pointing Firefox (Mac OSX) to 127.0.0.1:9000 I get 

```
com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: Error: Module "es6-promise" not found. (lessc.js#9)	at lessc.js:9 (anonymous)
	at lessc.js:2

     com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:215)

     com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:187)

     scala.util.Success$$anonfun$map$1.apply(Try.scala:206)

     scala.util.Try$.apply(Try.scala:161)

     scala.util.Success.map(Try.scala:206)

     scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)

     scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)

     scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)

     scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)

     scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)

     scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)

     scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)

     scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by kyleu** [comment]
Interesting, I couldn't reproduce that, I'm on a Mac as well (I grabbed the `boilerplay-master.zip` that GitHub lets you download). I just upgraded a few dependencies, please grab a fresh zip and try again. I haven't touched the LESS stuff in months...

**Comment by ppet** [comment]
Hi. Thx for your answer !
I just cloned a new install.
Changed line 51 of Server.scala in the project folder, to use Rhino instead of Node (I don't want to use Node):
//JsEngineKeys.engineType := JsEngineKeys.EngineType.Node,
    JsEngineKeys.engineType := JsEngineKeys.EngineType.Rhino,
and I get the exact same issue...
is there a special conf to apply when using Rhino ?

**Comment by ppet** [comment]
I tried to just comment out the JsEngineKeys.engineType line 51, so the search of Node failed and fell back automatically to Rhino.
So far so good... I let you know

**Comment by ppet** [comment]
it works !
IMHO. add a hint in the README for those who doesn't want to add Node to their box and are not expert of sbt-js configuration

**Comment by kyleu** [comment]
So, for future reference, this is the error you get without Node. Need to improve the error reporting.
