### ISSUE TITLE
Add jcenterRepo to get jwt-* for play-silhouette

### ISSUE THREAD

**Issue by rajit** [KyleU/boilerplay#2]
I found that I needed to make the following modification to resolve all dependencies:

```
--- a/project/Server.scala
+++ b/project/Server.scala
@@ -42,6 +42,7 @@ object Server {
     scalacOptions in Test ++= Seq("-Yrangepos"),

     libraryDependencies ++= dependencies,
+    resolvers ++= Seq(Resolver.jcenterRepo),

     routesGenerator := InjectedRoutesGenerator,
```

Without this, the `jwt-*` dependencies were not resolving. This issue is described here: https://github.com/sbt/sbt/issues/1820

**Comment by kyleu** [comment]
Thanks, good catch! I've corrected it by adding the resolver as you suggested.
