### ISSUE TITLE
uPickle will be deprecated

### ISSUE THREAD

**Issue by zoosky** [KyleU/boilerplay#23]
FYI 
See https://github.com/lihaoyi/upickle-pprint/issues/209

**Comment by kyleu** [comment]
Been meaning to handle this, thanks for the nudge. I'll switch to circe tonight.

**Comment by kyleu** [comment]
Switched to circe, it's a much better solution. When I initially wrote boilerplay, uPickle was the only game in town for JVM <-> JS interop. I'm really liking circe, thanks for submitting this issue!

**Comment by zoosky** [comment]
Wow. Great 👍
