### ISSUE TITLE
java.net.URISyntaxException when running BoilerPlay

### ISSUE THREAD

**Issue by Coestar** [KyleU/boilerplay#25]
Just cloned a fresh copy and ran into this issue: https://pastebin.com/raw/TMJb3LRq

Unsure why this is happening, any idea?

**Comment by kyleu** [comment]
Wow, that's deep in sbt's compile phase. I've got a windows machine, I'll test it with a fresh clone tonight, see if I can reproduce it. Thanks for the report.

**Comment by kyleu** [comment]
I spun up a fresh windows install, and got the same issue. It took forever, but I tracked it down to the `scalafix` plugin. I've disabled it for now, thanks for bringing it to my attention, I'll file a bug with them.
