### ISSUE TITLE
create extension hstore needs superuser

### ISSUE THREAD

**Issue by 5at** [KyleU/boilerplay#27]
After following instructions in "Getting Started" to create database and user the AuditSchema.sql fails as the "create extension if not exists hstore;" statement requires superuser access (version 9.5.9 of postgresql).

**Comment by kyleu** [comment]
Thanks for finding this, I added the hstore column recently, and usually run superuser locally.

**Comment by kyleu** [comment]
Hmm, looks like postgres requires superuser to allow the extension. I use an hstore for the audit stuff, I could update the documentation to require a superuser, but that seems like overreaching. It's only for the tags, I may just pull that out for now.

**Comment by padurean** [comment]
Hi, what is the best solution for this? For the moment i've altered the role to be superuser.

**Comment by kyleu** [comment]
The alternative would be creating the hstore extension with a superuser, then removing the extension creation from `./ddl`. Hstores are just too useful to give up :)
