### ISSUE TITLE
Postgres DDL syntax error

### ISSUE THREAD

**Issue by nkconnor** [KyleU/boilerplay#29]
Using Postgres 9.4, I get an error with the `if not exists` part of index creation
```
boilerplay=# create index if not exists "audit_act" on "audit" using btree ("act" asc nulls last);
ERROR:  syntax error at or near "not"
LINE 1: create index if not exists "audit_act" on "audit" using btre...
                        ^
```

**Comment by kyleu** [comment]
Yep, looks like "create index if not exists" is Postgres 9.5+

https://dba.stackexchange.com/questions/35616/create-index-if-it-does-not-exist

I'll update the doc, thanks for the report.
