### ISSUE TITLE
Registered and signed in, but still shown as guest

### ISSUE THREAD

**Issue by intracer** [KyleU/boilerplay#5]
![screenshot-boilerplay - google chrome](https://cloud.githubusercontent.com/assets/232811/8993198/286c37dc-370c-11e5-990f-813c74742821.png)

**Comment by kyleu** [comment]
Hmm, Websocket's failing too. I'll test it on Windows tonight.

**Comment by intracer** [comment]
Does not work in Google Chrome version 44.0.2403.125
Works in Firefox 39.0

**Comment by rajit** [comment]
Ah, I can corroborate. I raised issue #14 for the same thing.

If I use Safari (Mac OS X) I can login just fine. Can't login on Chrome.

**Comment by kyleu** [comment]
I've pushed a change that sets the host to "127.0.0.1", instead of "localhost". This works around the issue (access it via http://127.0.0.1:9000), I'll work on a permanent solution tonight.

**Comment by kyleu** [comment]
Resolved by changing the default host from localhost to 127.0.0.1 or a custom domain. I've checked in the change to 127.0.0.1.
