### ISSUE TITLE
Mysql backend

### ISSUE THREAD

**Issue by intracer** [KyleU/boilerplay#6]
postgresql-async supports mysql, changes to scala code should not be big, but there are many postrgres specific sql files in boilerplay
https://github.com/mauricio/postgresql-async/tree/master/mysql-async

**Comment by kyleu** [comment]
Most of the SQL is standard (with the exception of array columns), so a port to mysql-async would be pretty straightforward. But I don't think we'd want to support both in a single app, so maybe a fork would be the right solution.

**Comment by intracer** [comment]
Mysql does not have array columns support (as per https://dev.mysql.com/worklog/task/?id=2081)
so at least the users table has to be implemented differently
