### ISSUE TITLE
Slick backend

### ISSUE THREAD

**Issue by intracer** [KyleU/boilerplay#7]
Slick is part of typesafe stack, asynchronous since 3.0 and is a recommended backend for Play 2.4.
I think many will plan to use supported and mature DB backend, not  0.2 version basic libraries

**Comment by kyleu** [comment]
Slick's async support is still based on blocking JDBC, I think. I evaluated Slick when I started, but the postgres-async driver did exactly what I needed it to (and wow is it fast).
