### ISSUE TITLE
Create automated tests

### ISSUE THREAD

**Issue by intracer** [KyleU/boilerplay#8]

**Comment by kyleu** [comment]
I don't want to prescribe a specific test framework. I have some basic integration tests written, but all they really do is retrieve webpages and search for text. I'm happy to accept a pull request if you've got a favorite test library.

**Comment by intracer** [comment]
Without good test coverage one has no proof that the code is working. 
And it is not working for me for now #5 and other errors ( #9, #10 )
You might fix them, but have many others. 
And then you would not be able to change you code without being sure you did not break at least what is covered with tests
